/* DO NOT EDIT THIS FILE. IT IS GENERATED BY 'make version'*/

package siriusec

const (
	Version = "1.0.0"
)

// Gitref variable is automatically set to the output of git-describe
// during the build process
var Gitref string
