name: teleport-kube-agent
apiVersion: v2
version: "1.0.0"
appVersion: "1.0.0"
description: Siriusec provides a secure SSH and Kubernetes remote access solution that doesn't get in the way.
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Siriusec
