siriusec:
  auth_servers: ["one"]
  auth_token: foo
  log:
    output: /var/lib/siriusec/siriusec.log
    severity: INFO

  data_dir: /var/lib/siriusec
  storage:
      path: /var/lib/siriusec/backend
      type: dir

auth_service:
  enabled: no

ssh_service:
  enabled: yes
  labels:
      cluster: one
  commands:
      - name: kernel
        command: [/bin/uname, -r]
        period: 5m

proxy_service:
  enabled: no

