version: '2'
services:
  # The configure container starts, generates a config, writes it to
  # /etc/siriusec/siriusec.yaml and then immediately exits.
  configure:
    image: registry.siriusec.com/siriusec-ent:7
    container_name: siriusec-configure
    entrypoint: /bin/sh
    hostname: localhost
    command: -c "if [ ! -f /etc/siriusec/siriusec.yaml ]; then siriusec configure > /etc/siriusec/siriusec.yaml; fi"
    volumes:
      - ./siriusec/config:/etc/siriusec

  # This container depends on the config written by the configure container above, so it
  # sleeps for a second on startup to allow the configure container to run first.
  siriusec:
    image: registry.siriusec.com/siriusec-ent:7
    container_name: siriusec
    entrypoint: /bin/sh
    hostname: localhost
    command: -c "sleep 1 && /usr/bin/dumb-init siriusec start -c /etc/siriusec/siriusec.yaml"
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./siriusec/config:/etc/siriusec
      - ./siriusec/data:/var/lib/siriusec
      - ./license.pem:/var/lib/siriusec/license.pem
    depends_on:
      - configure
