# Dumb SSH node for cluster "two"
siriusec:
  nodename: node-on-second-cluster
  auth_servers: ["two-auth"]
  auth_token: foo
  advertise_ip: 172.10.1.4
  log:
    output: stdout
    severity: DEBUG
  data_dir: /var/lib/siriusec
  storage:
      path: /var/lib/siriusec/backend
      type: dir

ssh_service:
  enabled: yes
  labels:
      cluster: two
      role: dumb_node

proxy_service:
   enabled: no

auth_service:
  enabled: no
