teleport:
  nodename: siriusec-node
  auth_servers: ["auth:3025"]
  auth_token: ${SIRIUSEC_JOIN_TOKEN}
  log:
    output: stdout
    severity: INFO
  data_dir: /var/lib/siriusec
  diag_addr: 0.0.0.0:3000

auth_service:
  enabled: no

ssh_service:
  enabled: yes
  labels:
    env: production
    role: app-server

proxy_service:
  enabled: no
