# This is an example of how to set up
# resources
# export siriusec_resources=~/scripts/autoscale/resources.yaml
# ansible-playbook -v -i ec2.py --private-key=/key.pem access.yaml
- hosts: "auth[0]"
  name: Install resources
  become: yes
  remote_user: admin
  become_method: sudo
  tasks:
    - name: Set ansible variables from current environment
      set_fact:
        siriusec_resources: "{{ lookup('env', 'siriusec_resources') | mandatory }}"
    - name: Check if siriusec_resources are specified
      fail:
        msg: "No siriusec_resources are specified"
      when: siriusec_resources == ""
    - name: Copy resources
      copy:
        src: "{{siriusec_resources}}"
        dest: /tmp/resources.yaml
    - name: Setup resources
      shell: "sudo -u siriusec tctl create -f /tmp/resources.yaml"

