clusterName: test-gcp-cluster
chartMode: gcp
gcp:
  projectId: gcpproj-123456
  backendTable: test-siriusec-firestore-storage-collection
  auditLogTable: test-siriusec-firestore-auditlog-collection
  sessionRecordingBucket: test-gcp-session-storage-bucket
acme: true
acmeEmail: test@email.com
labels:
  env: gcp
