{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "siriusec.serviceAccountName" . }}
  labels:
{{ include "siriusec.labels" . | indent 4 }}
{{- end -}}
