authToken: auth-token
proxyAddr: proxy.example.com:3080
roles: kube
kubeClusterName: test-kube-cluster
clusterRoleName: siriusec-kube-agent-test
clusterRoleBindingName: siriusec-kube-agent-test
serviceAccountName: siriusec-kube-agent-test
